<?php
/**
 * FineTunesApi
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAI API
 *
 * OpenAI is an AI research and deployment company. Our mission is to ensure that artificial general intelligence benefits all of humanity.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAI\Client\ApiException;
use OpenAI\Client\Configuration;
use OpenAI\Client\HeaderSelector;
use OpenAI\Client\ObjectSerializer;

/**
 * FineTunesApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FineTunesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getFineTune
     *
     * Gets info about the fine-tune job.
     *
     * @param  string $fine_tune_id The ID of the fine-tune job (required)
     * @param  string $open_ai_organization open_ai_organization (optional)
     *
     * @throws \OpenAI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAI\Client\Model\FineTune
     */
    public function getFineTune($fine_tune_id, $open_ai_organization = null)
    {
        list($response) = $this->getFineTuneWithHttpInfo($fine_tune_id, $open_ai_organization);
        return $response;
    }

    /**
     * Operation getFineTuneWithHttpInfo
     *
     * Gets info about the fine-tune job.
     *
     * @param  string $fine_tune_id The ID of the fine-tune job (required)
     * @param  string $open_ai_organization (optional)
     *
     * @throws \OpenAI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAI\Client\Model\FineTune, HTTP status code, HTTP response headers (array of strings)
     */
    public function getFineTuneWithHttpInfo($fine_tune_id, $open_ai_organization = null)
    {
        $request = $this->getFineTuneRequest($fine_tune_id, $open_ai_organization);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAI\Client\Model\FineTune' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAI\Client\Model\FineTune', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAI\Client\Model\FineTune';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAI\Client\Model\FineTune',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getFineTuneAsync
     *
     * Gets info about the fine-tune job.
     *
     * @param  string $fine_tune_id The ID of the fine-tune job (required)
     * @param  string $open_ai_organization (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFineTuneAsync($fine_tune_id, $open_ai_organization = null)
    {
        return $this->getFineTuneAsyncWithHttpInfo($fine_tune_id, $open_ai_organization)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getFineTuneAsyncWithHttpInfo
     *
     * Gets info about the fine-tune job.
     *
     * @param  string $fine_tune_id The ID of the fine-tune job (required)
     * @param  string $open_ai_organization (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFineTuneAsyncWithHttpInfo($fine_tune_id, $open_ai_organization = null)
    {
        $returnType = '\OpenAI\Client\Model\FineTune';
        $request = $this->getFineTuneRequest($fine_tune_id, $open_ai_organization);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getFineTune'
     *
     * @param  string $fine_tune_id The ID of the fine-tune job (required)
     * @param  string $open_ai_organization (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getFineTuneRequest($fine_tune_id, $open_ai_organization = null)
    {
        // verify the required parameter 'fine_tune_id' is set
        if ($fine_tune_id === null || (is_array($fine_tune_id) && count($fine_tune_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $fine_tune_id when calling getFineTune'
            );
        }

        $resourcePath = '/fine-tunes/{fine_tune_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($open_ai_organization !== null) {
            $headerParams['OpenAI-Organization'] = ObjectSerializer::toHeaderValue($open_ai_organization);
        }

        // path params
        if ($fine_tune_id !== null) {
            $resourcePath = str_replace(
                '{' . 'fine_tune_id' . '}',
                ObjectSerializer::toPathValue($fine_tune_id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getFineTuneEvents
     *
     * Get fine-grained status updates for a fine-tune job.
     *
     * @param  string $fine_tune_id The ID of the fine-tune job to get events for. (required)
     * @param  string $open_ai_organization open_ai_organization (optional)
     * @param  bool $stream Whether to stream events for the fine-tune job. If set to true, events will be sent as data-only server-sent events as they become available. (optional)
     *
     * @throws \OpenAI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAI\Client\Model\FineTuneEvents
     */
    public function getFineTuneEvents($fine_tune_id, $open_ai_organization = null, $stream = null)
    {
        list($response) = $this->getFineTuneEventsWithHttpInfo($fine_tune_id, $open_ai_organization, $stream);
        return $response;
    }

    /**
     * Operation getFineTuneEventsWithHttpInfo
     *
     * Get fine-grained status updates for a fine-tune job.
     *
     * @param  string $fine_tune_id The ID of the fine-tune job to get events for. (required)
     * @param  string $open_ai_organization (optional)
     * @param  bool $stream Whether to stream events for the fine-tune job. If set to true, events will be sent as data-only server-sent events as they become available. (optional)
     *
     * @throws \OpenAI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAI\Client\Model\FineTuneEvents, HTTP status code, HTTP response headers (array of strings)
     */
    public function getFineTuneEventsWithHttpInfo($fine_tune_id, $open_ai_organization = null, $stream = null)
    {
        $request = $this->getFineTuneEventsRequest($fine_tune_id, $open_ai_organization, $stream);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAI\Client\Model\FineTuneEvents' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAI\Client\Model\FineTuneEvents', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAI\Client\Model\FineTuneEvents';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAI\Client\Model\FineTuneEvents',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getFineTuneEventsAsync
     *
     * Get fine-grained status updates for a fine-tune job.
     *
     * @param  string $fine_tune_id The ID of the fine-tune job to get events for. (required)
     * @param  string $open_ai_organization (optional)
     * @param  bool $stream Whether to stream events for the fine-tune job. If set to true, events will be sent as data-only server-sent events as they become available. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFineTuneEventsAsync($fine_tune_id, $open_ai_organization = null, $stream = null)
    {
        return $this->getFineTuneEventsAsyncWithHttpInfo($fine_tune_id, $open_ai_organization, $stream)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getFineTuneEventsAsyncWithHttpInfo
     *
     * Get fine-grained status updates for a fine-tune job.
     *
     * @param  string $fine_tune_id The ID of the fine-tune job to get events for. (required)
     * @param  string $open_ai_organization (optional)
     * @param  bool $stream Whether to stream events for the fine-tune job. If set to true, events will be sent as data-only server-sent events as they become available. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFineTuneEventsAsyncWithHttpInfo($fine_tune_id, $open_ai_organization = null, $stream = null)
    {
        $returnType = '\OpenAI\Client\Model\FineTuneEvents';
        $request = $this->getFineTuneEventsRequest($fine_tune_id, $open_ai_organization, $stream);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getFineTuneEvents'
     *
     * @param  string $fine_tune_id The ID of the fine-tune job to get events for. (required)
     * @param  string $open_ai_organization (optional)
     * @param  bool $stream Whether to stream events for the fine-tune job. If set to true, events will be sent as data-only server-sent events as they become available. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getFineTuneEventsRequest($fine_tune_id, $open_ai_organization = null, $stream = null)
    {
        // verify the required parameter 'fine_tune_id' is set
        if ($fine_tune_id === null || (is_array($fine_tune_id) && count($fine_tune_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $fine_tune_id when calling getFineTuneEvents'
            );
        }

        $resourcePath = '/fine-tunes/{fine_tune_id}/events';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($stream !== null) {
            if('form' === 'form' && is_array($stream)) {
                foreach($stream as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['stream'] = $stream;
            }
        }

        // header params
        if ($open_ai_organization !== null) {
            $headerParams['OpenAI-Organization'] = ObjectSerializer::toHeaderValue($open_ai_organization);
        }

        // path params
        if ($fine_tune_id !== null) {
            $resourcePath = str_replace(
                '{' . 'fine_tune_id' . '}',
                ObjectSerializer::toPathValue($fine_tune_id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getFineTunes
     *
     * List your organization&#39;s fine-tuning jobs
     *
     * @param  string $open_ai_organization open_ai_organization (optional)
     *
     * @throws \OpenAI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAI\Client\Model\FineTunes
     */
    public function getFineTunes($open_ai_organization = null)
    {
        list($response) = $this->getFineTunesWithHttpInfo($open_ai_organization);
        return $response;
    }

    /**
     * Operation getFineTunesWithHttpInfo
     *
     * List your organization&#39;s fine-tuning jobs
     *
     * @param  string $open_ai_organization (optional)
     *
     * @throws \OpenAI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAI\Client\Model\FineTunes, HTTP status code, HTTP response headers (array of strings)
     */
    public function getFineTunesWithHttpInfo($open_ai_organization = null)
    {
        $request = $this->getFineTunesRequest($open_ai_organization);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAI\Client\Model\FineTunes' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAI\Client\Model\FineTunes', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAI\Client\Model\FineTunes';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAI\Client\Model\FineTunes',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getFineTunesAsync
     *
     * List your organization&#39;s fine-tuning jobs
     *
     * @param  string $open_ai_organization (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFineTunesAsync($open_ai_organization = null)
    {
        return $this->getFineTunesAsyncWithHttpInfo($open_ai_organization)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getFineTunesAsyncWithHttpInfo
     *
     * List your organization&#39;s fine-tuning jobs
     *
     * @param  string $open_ai_organization (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFineTunesAsyncWithHttpInfo($open_ai_organization = null)
    {
        $returnType = '\OpenAI\Client\Model\FineTunes';
        $request = $this->getFineTunesRequest($open_ai_organization);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getFineTunes'
     *
     * @param  string $open_ai_organization (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getFineTunesRequest($open_ai_organization = null)
    {

        $resourcePath = '/fine-tunes';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($open_ai_organization !== null) {
            $headerParams['OpenAI-Organization'] = ObjectSerializer::toHeaderValue($open_ai_organization);
        }



        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postFineTuneCancel
     *
     * Immediately cancel a fine-tune job.
     *
     * @param  string $fine_tune_id The ID of the fine-tune job to cancel (required)
     * @param  string $open_ai_organization open_ai_organization (optional)
     *
     * @throws \OpenAI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAI\Client\Model\FineTune
     */
    public function postFineTuneCancel($fine_tune_id, $open_ai_organization = null)
    {
        list($response) = $this->postFineTuneCancelWithHttpInfo($fine_tune_id, $open_ai_organization);
        return $response;
    }

    /**
     * Operation postFineTuneCancelWithHttpInfo
     *
     * Immediately cancel a fine-tune job.
     *
     * @param  string $fine_tune_id The ID of the fine-tune job to cancel (required)
     * @param  string $open_ai_organization (optional)
     *
     * @throws \OpenAI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAI\Client\Model\FineTune, HTTP status code, HTTP response headers (array of strings)
     */
    public function postFineTuneCancelWithHttpInfo($fine_tune_id, $open_ai_organization = null)
    {
        $request = $this->postFineTuneCancelRequest($fine_tune_id, $open_ai_organization);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAI\Client\Model\FineTune' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAI\Client\Model\FineTune', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAI\Client\Model\FineTune';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAI\Client\Model\FineTune',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postFineTuneCancelAsync
     *
     * Immediately cancel a fine-tune job.
     *
     * @param  string $fine_tune_id The ID of the fine-tune job to cancel (required)
     * @param  string $open_ai_organization (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postFineTuneCancelAsync($fine_tune_id, $open_ai_organization = null)
    {
        return $this->postFineTuneCancelAsyncWithHttpInfo($fine_tune_id, $open_ai_organization)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postFineTuneCancelAsyncWithHttpInfo
     *
     * Immediately cancel a fine-tune job.
     *
     * @param  string $fine_tune_id The ID of the fine-tune job to cancel (required)
     * @param  string $open_ai_organization (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postFineTuneCancelAsyncWithHttpInfo($fine_tune_id, $open_ai_organization = null)
    {
        $returnType = '\OpenAI\Client\Model\FineTune';
        $request = $this->postFineTuneCancelRequest($fine_tune_id, $open_ai_organization);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postFineTuneCancel'
     *
     * @param  string $fine_tune_id The ID of the fine-tune job to cancel (required)
     * @param  string $open_ai_organization (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postFineTuneCancelRequest($fine_tune_id, $open_ai_organization = null)
    {
        // verify the required parameter 'fine_tune_id' is set
        if ($fine_tune_id === null || (is_array($fine_tune_id) && count($fine_tune_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $fine_tune_id when calling postFineTuneCancel'
            );
        }

        $resourcePath = '/fine-tunes/{fine_tune_id}/cancel';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($open_ai_organization !== null) {
            $headerParams['OpenAI-Organization'] = ObjectSerializer::toHeaderValue($open_ai_organization);
        }

        // path params
        if ($fine_tune_id !== null) {
            $resourcePath = str_replace(
                '{' . 'fine_tune_id' . '}',
                ObjectSerializer::toPathValue($fine_tune_id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postFineTunes
     *
     * Creates a job that fine-tunes a specified model from a given dataset.
     *
     * @param  string $open_ai_organization open_ai_organization (optional)
     * @param  \OpenAI\Client\Model\FineTunesPayload $fine_tunes_payload fine_tunes_payload (optional)
     *
     * @throws \OpenAI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAI\Client\Model\FineTune
     */
    public function postFineTunes($open_ai_organization = null, $fine_tunes_payload = null)
    {
        list($response) = $this->postFineTunesWithHttpInfo($open_ai_organization, $fine_tunes_payload);
        return $response;
    }

    /**
     * Operation postFineTunesWithHttpInfo
     *
     * Creates a job that fine-tunes a specified model from a given dataset.
     *
     * @param  string $open_ai_organization (optional)
     * @param  \OpenAI\Client\Model\FineTunesPayload $fine_tunes_payload (optional)
     *
     * @throws \OpenAI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAI\Client\Model\FineTune, HTTP status code, HTTP response headers (array of strings)
     */
    public function postFineTunesWithHttpInfo($open_ai_organization = null, $fine_tunes_payload = null)
    {
        $request = $this->postFineTunesRequest($open_ai_organization, $fine_tunes_payload);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAI\Client\Model\FineTune' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAI\Client\Model\FineTune', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAI\Client\Model\FineTune';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAI\Client\Model\FineTune',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postFineTunesAsync
     *
     * Creates a job that fine-tunes a specified model from a given dataset.
     *
     * @param  string $open_ai_organization (optional)
     * @param  \OpenAI\Client\Model\FineTunesPayload $fine_tunes_payload (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postFineTunesAsync($open_ai_organization = null, $fine_tunes_payload = null)
    {
        return $this->postFineTunesAsyncWithHttpInfo($open_ai_organization, $fine_tunes_payload)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postFineTunesAsyncWithHttpInfo
     *
     * Creates a job that fine-tunes a specified model from a given dataset.
     *
     * @param  string $open_ai_organization (optional)
     * @param  \OpenAI\Client\Model\FineTunesPayload $fine_tunes_payload (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postFineTunesAsyncWithHttpInfo($open_ai_organization = null, $fine_tunes_payload = null)
    {
        $returnType = '\OpenAI\Client\Model\FineTune';
        $request = $this->postFineTunesRequest($open_ai_organization, $fine_tunes_payload);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postFineTunes'
     *
     * @param  string $open_ai_organization (optional)
     * @param  \OpenAI\Client\Model\FineTunesPayload $fine_tunes_payload (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postFineTunesRequest($open_ai_organization = null, $fine_tunes_payload = null)
    {

        $resourcePath = '/fine-tunes';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($open_ai_organization !== null) {
            $headerParams['OpenAI-Organization'] = ObjectSerializer::toHeaderValue($open_ai_organization);
        }



        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($fine_tunes_payload)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($fine_tunes_payload));
            } else {
                $httpBody = $fine_tunes_payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
