<?php
/**
 * ImagesApi
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAI API
 *
 * OpenAI is an AI research and deployment company. Our mission is to ensure that artificial general intelligence benefits all of humanity.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAI\Client\ApiException;
use OpenAI\Client\Configuration;
use OpenAI\Client\HeaderSelector;
use OpenAI\Client\ObjectSerializer;

/**
 * ImagesApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ImagesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation postImagesEdits
     *
     * Creates an edited or extended image given an original image and a prompt.
     *
     * @param  string $open_ai_organization open_ai_organization (optional)
     * @param  \SplFileObject $image An additional image whose fully transparent areas (e.g. where alpha is zero) indicate where image should be edited. Must be a valid PNG file, less than 4MB, and have the same dimensions as image. (optional)
     * @param  \SplFileObject $mark The image to edit. Must be a valid PNG file, less than 4MB, and square. (optional)
     * @param  int $n The number of images to generate. Must be between 1 and 10. (optional, default to 1)
     * @param  string $size The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024. (optional, default to '1024x1024')
     * @param  string $response_format The format in which the generated images are returned. Must be one of url or b64_json. (optional, default to 'url')
     * @param  string $user A unique identifier representing your end-user, which will help OpenAI to monitor and detect abuse. (optional, default to 'null')
     *
     * @throws \OpenAI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAI\Client\Model\Images
     */
    public function postImagesEdits($open_ai_organization = null, $image = null, $mark = null, $n = 1, $size = '1024x1024', $response_format = 'url', $user = 'null')
    {
        list($response) = $this->postImagesEditsWithHttpInfo($open_ai_organization, $image, $mark, $n, $size, $response_format, $user);
        return $response;
    }

    /**
     * Operation postImagesEditsWithHttpInfo
     *
     * Creates an edited or extended image given an original image and a prompt.
     *
     * @param  string $open_ai_organization (optional)
     * @param  \SplFileObject $image An additional image whose fully transparent areas (e.g. where alpha is zero) indicate where image should be edited. Must be a valid PNG file, less than 4MB, and have the same dimensions as image. (optional)
     * @param  \SplFileObject $mark The image to edit. Must be a valid PNG file, less than 4MB, and square. (optional)
     * @param  int $n The number of images to generate. Must be between 1 and 10. (optional, default to 1)
     * @param  string $size The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024. (optional, default to '1024x1024')
     * @param  string $response_format The format in which the generated images are returned. Must be one of url or b64_json. (optional, default to 'url')
     * @param  string $user A unique identifier representing your end-user, which will help OpenAI to monitor and detect abuse. (optional, default to 'null')
     *
     * @throws \OpenAI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAI\Client\Model\Images, HTTP status code, HTTP response headers (array of strings)
     */
    public function postImagesEditsWithHttpInfo($open_ai_organization = null, $image = null, $mark = null, $n = 1, $size = '1024x1024', $response_format = 'url', $user = 'null')
    {
        $request = $this->postImagesEditsRequest($open_ai_organization, $image, $mark, $n, $size, $response_format, $user);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAI\Client\Model\Images' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAI\Client\Model\Images', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAI\Client\Model\Images';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAI\Client\Model\Images',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postImagesEditsAsync
     *
     * Creates an edited or extended image given an original image and a prompt.
     *
     * @param  string $open_ai_organization (optional)
     * @param  \SplFileObject $image An additional image whose fully transparent areas (e.g. where alpha is zero) indicate where image should be edited. Must be a valid PNG file, less than 4MB, and have the same dimensions as image. (optional)
     * @param  \SplFileObject $mark The image to edit. Must be a valid PNG file, less than 4MB, and square. (optional)
     * @param  int $n The number of images to generate. Must be between 1 and 10. (optional, default to 1)
     * @param  string $size The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024. (optional, default to '1024x1024')
     * @param  string $response_format The format in which the generated images are returned. Must be one of url or b64_json. (optional, default to 'url')
     * @param  string $user A unique identifier representing your end-user, which will help OpenAI to monitor and detect abuse. (optional, default to 'null')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postImagesEditsAsync($open_ai_organization = null, $image = null, $mark = null, $n = 1, $size = '1024x1024', $response_format = 'url', $user = 'null')
    {
        return $this->postImagesEditsAsyncWithHttpInfo($open_ai_organization, $image, $mark, $n, $size, $response_format, $user)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postImagesEditsAsyncWithHttpInfo
     *
     * Creates an edited or extended image given an original image and a prompt.
     *
     * @param  string $open_ai_organization (optional)
     * @param  \SplFileObject $image An additional image whose fully transparent areas (e.g. where alpha is zero) indicate where image should be edited. Must be a valid PNG file, less than 4MB, and have the same dimensions as image. (optional)
     * @param  \SplFileObject $mark The image to edit. Must be a valid PNG file, less than 4MB, and square. (optional)
     * @param  int $n The number of images to generate. Must be between 1 and 10. (optional, default to 1)
     * @param  string $size The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024. (optional, default to '1024x1024')
     * @param  string $response_format The format in which the generated images are returned. Must be one of url or b64_json. (optional, default to 'url')
     * @param  string $user A unique identifier representing your end-user, which will help OpenAI to monitor and detect abuse. (optional, default to 'null')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postImagesEditsAsyncWithHttpInfo($open_ai_organization = null, $image = null, $mark = null, $n = 1, $size = '1024x1024', $response_format = 'url', $user = 'null')
    {
        $returnType = '\OpenAI\Client\Model\Images';
        $request = $this->postImagesEditsRequest($open_ai_organization, $image, $mark, $n, $size, $response_format, $user);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postImagesEdits'
     *
     * @param  string $open_ai_organization (optional)
     * @param  \SplFileObject $image An additional image whose fully transparent areas (e.g. where alpha is zero) indicate where image should be edited. Must be a valid PNG file, less than 4MB, and have the same dimensions as image. (optional)
     * @param  \SplFileObject $mark The image to edit. Must be a valid PNG file, less than 4MB, and square. (optional)
     * @param  int $n The number of images to generate. Must be between 1 and 10. (optional, default to 1)
     * @param  string $size The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024. (optional, default to '1024x1024')
     * @param  string $response_format The format in which the generated images are returned. Must be one of url or b64_json. (optional, default to 'url')
     * @param  string $user A unique identifier representing your end-user, which will help OpenAI to monitor and detect abuse. (optional, default to 'null')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postImagesEditsRequest($open_ai_organization = null, $image = null, $mark = null, $n = 1, $size = '1024x1024', $response_format = 'url', $user = 'null')
    {

        $resourcePath = '/images/edits';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($open_ai_organization !== null) {
            $headerParams['OpenAI-Organization'] = ObjectSerializer::toHeaderValue($open_ai_organization);
        }


        // form params
        if ($image !== null) {
            $multipart = true;
            $formParams['image'] = [];
            $paramFiles = is_array($image) ? $image : [$image];
            foreach ($paramFiles as $paramFile) {
                $formParams['image'][] = \GuzzleHttp\Psr7\try_fopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }
        // form params
        if ($mark !== null) {
            $multipart = true;
            $formParams['mark'] = [];
            $paramFiles = is_array($mark) ? $mark : [$mark];
            foreach ($paramFiles as $paramFile) {
                $formParams['mark'][] = \GuzzleHttp\Psr7\try_fopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }
        // form params
        if ($n !== null) {
            $formParams['n'] = ObjectSerializer::toFormValue($n);
        }
        // form params
        if ($size !== null) {
            $formParams['size'] = ObjectSerializer::toFormValue($size);
        }
        // form params
        if ($response_format !== null) {
            $formParams['response_format'] = ObjectSerializer::toFormValue($response_format);
        }
        // form params
        if ($user !== null) {
            $formParams['user'] = ObjectSerializer::toFormValue($user);
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['multipart/form-data']
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postImagesGenerations
     *
     * Given a prompt and/or an input image, the model will generate a new image.
     *
     * @param  string $open_ai_organization open_ai_organization (optional)
     * @param  \OpenAI\Client\Model\ImagesGenerationsPayload $images_generations_payload images_generations_payload (optional)
     *
     * @throws \OpenAI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAI\Client\Model\Images
     */
    public function postImagesGenerations($open_ai_organization = null, $images_generations_payload = null)
    {
        list($response) = $this->postImagesGenerationsWithHttpInfo($open_ai_organization, $images_generations_payload);
        return $response;
    }

    /**
     * Operation postImagesGenerationsWithHttpInfo
     *
     * Given a prompt and/or an input image, the model will generate a new image.
     *
     * @param  string $open_ai_organization (optional)
     * @param  \OpenAI\Client\Model\ImagesGenerationsPayload $images_generations_payload (optional)
     *
     * @throws \OpenAI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAI\Client\Model\Images, HTTP status code, HTTP response headers (array of strings)
     */
    public function postImagesGenerationsWithHttpInfo($open_ai_organization = null, $images_generations_payload = null)
    {
        $request = $this->postImagesGenerationsRequest($open_ai_organization, $images_generations_payload);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAI\Client\Model\Images' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAI\Client\Model\Images', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAI\Client\Model\Images';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAI\Client\Model\Images',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postImagesGenerationsAsync
     *
     * Given a prompt and/or an input image, the model will generate a new image.
     *
     * @param  string $open_ai_organization (optional)
     * @param  \OpenAI\Client\Model\ImagesGenerationsPayload $images_generations_payload (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postImagesGenerationsAsync($open_ai_organization = null, $images_generations_payload = null)
    {
        return $this->postImagesGenerationsAsyncWithHttpInfo($open_ai_organization, $images_generations_payload)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postImagesGenerationsAsyncWithHttpInfo
     *
     * Given a prompt and/or an input image, the model will generate a new image.
     *
     * @param  string $open_ai_organization (optional)
     * @param  \OpenAI\Client\Model\ImagesGenerationsPayload $images_generations_payload (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postImagesGenerationsAsyncWithHttpInfo($open_ai_organization = null, $images_generations_payload = null)
    {
        $returnType = '\OpenAI\Client\Model\Images';
        $request = $this->postImagesGenerationsRequest($open_ai_organization, $images_generations_payload);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postImagesGenerations'
     *
     * @param  string $open_ai_organization (optional)
     * @param  \OpenAI\Client\Model\ImagesGenerationsPayload $images_generations_payload (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postImagesGenerationsRequest($open_ai_organization = null, $images_generations_payload = null)
    {

        $resourcePath = '/images/generations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($open_ai_organization !== null) {
            $headerParams['OpenAI-Organization'] = ObjectSerializer::toHeaderValue($open_ai_organization);
        }



        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($images_generations_payload)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($images_generations_payload));
            } else {
                $httpBody = $images_generations_payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postImagesVariations
     *
     * Creates a variation of a given image.
     *
     * @param  string $open_ai_organization open_ai_organization (optional)
     * @param  \SplFileObject $image The image to use as the basis for the variation(s). Must be a valid PNG file, less than 4MB, and square. (optional)
     * @param  int $n The number of images to generate. Must be between 1 and 10. (optional, default to 1)
     * @param  string $size The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024. (optional, default to '1024x1024')
     * @param  string $response_format The format in which the generated images are returned. Must be one of url or b64_json. (optional, default to 'url')
     * @param  string $user A unique identifier representing your end-user, which will help OpenAI to monitor and detect abuse. (optional, default to 'null')
     *
     * @throws \OpenAI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAI\Client\Model\Images
     */
    public function postImagesVariations($open_ai_organization = null, $image = null, $n = 1, $size = '1024x1024', $response_format = 'url', $user = 'null')
    {
        list($response) = $this->postImagesVariationsWithHttpInfo($open_ai_organization, $image, $n, $size, $response_format, $user);
        return $response;
    }

    /**
     * Operation postImagesVariationsWithHttpInfo
     *
     * Creates a variation of a given image.
     *
     * @param  string $open_ai_organization (optional)
     * @param  \SplFileObject $image The image to use as the basis for the variation(s). Must be a valid PNG file, less than 4MB, and square. (optional)
     * @param  int $n The number of images to generate. Must be between 1 and 10. (optional, default to 1)
     * @param  string $size The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024. (optional, default to '1024x1024')
     * @param  string $response_format The format in which the generated images are returned. Must be one of url or b64_json. (optional, default to 'url')
     * @param  string $user A unique identifier representing your end-user, which will help OpenAI to monitor and detect abuse. (optional, default to 'null')
     *
     * @throws \OpenAI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAI\Client\Model\Images, HTTP status code, HTTP response headers (array of strings)
     */
    public function postImagesVariationsWithHttpInfo($open_ai_organization = null, $image = null, $n = 1, $size = '1024x1024', $response_format = 'url', $user = 'null')
    {
        $request = $this->postImagesVariationsRequest($open_ai_organization, $image, $n, $size, $response_format, $user);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAI\Client\Model\Images' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAI\Client\Model\Images', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAI\Client\Model\Images';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAI\Client\Model\Images',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postImagesVariationsAsync
     *
     * Creates a variation of a given image.
     *
     * @param  string $open_ai_organization (optional)
     * @param  \SplFileObject $image The image to use as the basis for the variation(s). Must be a valid PNG file, less than 4MB, and square. (optional)
     * @param  int $n The number of images to generate. Must be between 1 and 10. (optional, default to 1)
     * @param  string $size The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024. (optional, default to '1024x1024')
     * @param  string $response_format The format in which the generated images are returned. Must be one of url or b64_json. (optional, default to 'url')
     * @param  string $user A unique identifier representing your end-user, which will help OpenAI to monitor and detect abuse. (optional, default to 'null')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postImagesVariationsAsync($open_ai_organization = null, $image = null, $n = 1, $size = '1024x1024', $response_format = 'url', $user = 'null')
    {
        return $this->postImagesVariationsAsyncWithHttpInfo($open_ai_organization, $image, $n, $size, $response_format, $user)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postImagesVariationsAsyncWithHttpInfo
     *
     * Creates a variation of a given image.
     *
     * @param  string $open_ai_organization (optional)
     * @param  \SplFileObject $image The image to use as the basis for the variation(s). Must be a valid PNG file, less than 4MB, and square. (optional)
     * @param  int $n The number of images to generate. Must be between 1 and 10. (optional, default to 1)
     * @param  string $size The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024. (optional, default to '1024x1024')
     * @param  string $response_format The format in which the generated images are returned. Must be one of url or b64_json. (optional, default to 'url')
     * @param  string $user A unique identifier representing your end-user, which will help OpenAI to monitor and detect abuse. (optional, default to 'null')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postImagesVariationsAsyncWithHttpInfo($open_ai_organization = null, $image = null, $n = 1, $size = '1024x1024', $response_format = 'url', $user = 'null')
    {
        $returnType = '\OpenAI\Client\Model\Images';
        $request = $this->postImagesVariationsRequest($open_ai_organization, $image, $n, $size, $response_format, $user);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postImagesVariations'
     *
     * @param  string $open_ai_organization (optional)
     * @param  \SplFileObject $image The image to use as the basis for the variation(s). Must be a valid PNG file, less than 4MB, and square. (optional)
     * @param  int $n The number of images to generate. Must be between 1 and 10. (optional, default to 1)
     * @param  string $size The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024. (optional, default to '1024x1024')
     * @param  string $response_format The format in which the generated images are returned. Must be one of url or b64_json. (optional, default to 'url')
     * @param  string $user A unique identifier representing your end-user, which will help OpenAI to monitor and detect abuse. (optional, default to 'null')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postImagesVariationsRequest($open_ai_organization = null, $image = null, $n = 1, $size = '1024x1024', $response_format = 'url', $user = 'null')
    {

        $resourcePath = '/images/variations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($open_ai_organization !== null) {
            $headerParams['OpenAI-Organization'] = ObjectSerializer::toHeaderValue($open_ai_organization);
        }


        // form params
        if ($image !== null) {
            $multipart = true;
            $formParams['image'] = [];
            $paramFiles = is_array($image) ? $image : [$image];
            foreach ($paramFiles as $paramFile) {
                $formParams['image'][] = \GuzzleHttp\Psr7\try_fopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }
        // form params
        if ($n !== null) {
            $formParams['n'] = ObjectSerializer::toFormValue($n);
        }
        // form params
        if ($size !== null) {
            $formParams['size'] = ObjectSerializer::toFormValue($size);
        }
        // form params
        if ($response_format !== null) {
            $formParams['response_format'] = ObjectSerializer::toFormValue($response_format);
        }
        // form params
        if ($user !== null) {
            $formParams['user'] = ObjectSerializer::toFormValue($user);
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['multipart/form-data']
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
