<?php
/**
 * FineTunesApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAI API
 *
 * OpenAI is an AI research and deployment company. Our mission is to ensure that artificial general intelligence benefits all of humanity.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAI\Client\Test\Api;

use \OpenAI\Client\Configuration;
use \OpenAI\Client\ApiException;
use \OpenAI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FineTunesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FineTunesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getFineTune
     *
     * Gets info about the fine-tune job..
     *
     */
    public function testGetFineTune()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFineTuneEvents
     *
     * Get fine-grained status updates for a fine-tune job..
     *
     */
    public function testGetFineTuneEvents()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFineTunes
     *
     * List your organization's fine-tuning jobs.
     *
     */
    public function testGetFineTunes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postFineTuneCancel
     *
     * Immediately cancel a fine-tune job..
     *
     */
    public function testPostFineTuneCancel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postFineTunes
     *
     * Creates a job that fine-tunes a specified model from a given dataset..
     *
     */
    public function testPostFineTunes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
